repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff Linter & Formatter (auto-fix)
        entry: python -m ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
        args: ["."]
        pass_filenames: false

      - id: pylint
        name: Pylint Static Analysis
        entry: python -m pylint
        language: system
        types: [python]
        args: ["."]
        pass_filenames: false

      - id: mypy
        name: Mypy Type Checker
        entry: python -m mypy
        language: system
        types: [python]
        args: ["."]
        pass_filenames: false

      - id: bandit
        name: Bandit Security Check
        entry: python -m bandit -r
        language: system
        types: [python]
        args: ["."]
        pass_filenames: false
