name: Quality Checks

on:
  pull_request:
  push:

jobs:
  lint-and-scan:
    name: Ruff / pylint / mypy / Bandit
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy bandit pylint

      - name: Ruff
        run: ruff check --fix --exit-non-zero-on-fix .

      - name: Pylint
        run: pylint .

      - name: mypy
        run: mypy .

      - name: Bandit
        run: bandit -r .
